name: "Frogbot Scan Pull Request"
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: read
  security-events: write
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: jfrog/frogbot@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_FAIL: "TRUE"
          JF_MIN_SEVERITY: "Medium"
          JF_INCLUDE_ALL_VULNERABILITIES: "FALSE"
          JF_UPLOAD_PR_SECURITY_RESULTS_TO_VCS: "TRUE"
