name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  push:
    branches: [master, main]
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    name: Scan Repository (${{ matrix.branch }} branch)
    strategy:
      matrix:
        branch: ["master"]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}

      - uses: jfrog/frogbot@v3
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_UPLOAD_SBOM_TO_VCS: "TRUE"
